fix: [#66681] Use `StatistikForm` in `StatistikChoicesView`
Otherwise the view responds with a 500 error:

```
Internal Server Error: /statistik/choices
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/statistik/views.py", line 346, in form_valid
    data["produkttype_eksport"] = self.get_data(
                                  ^^^^^^^^^^^^^^
  File "/app/statistik/views.py", line 284, in get_data
    qs, grouping_fields, ordering_fields = self.get_queryset(form, fields)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/statistik/views.py", line 29, in get_queryset
    annotate_bonusadjusted = cleaned_data["disregard_bonus_reports"]
                             ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'disregard_bonus_reports'
```

as the field `disregard_bonus_reports` is only defined in `StatistikForm` (and not `StatistikBaseForm`.)